[package]
name = "ruroutes-api"
version = "0.1.0"
authors = ["Adam Piziak <adam.piziak@rutgers.edu>"]

[dependencies]
rocket = "0.4.0-rc.1"
reqwest = "0.9.4"
redis = "0.9.1"
r2d2 = "0.8.2"
r2d2_redis = "0.8.0"
serde = "1.0.80"
serde_derive = "1.0.80"
serde_json = "1.0.32"
