[package]
name = "rutgers_link"
version = "0.1.0"
authors = ["Adam Piziak <adam.piziak@rutgers.edu>"]

[dependencies]
rocket = "0.3.5"
rocket_codegen = "0.3.5"
reqwest = "0.8.2"
redis = "0.8.0"
r2d2 = "0.8.2"
r2d2_redis = "0.7.0"
